# Generated by Django 3.0.5 on 2023-05-19 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0006_auto_20230517_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Order Confirmed', 'Order Confirmed'), ('Out of stock', 'Out of stock'), ('Delivered', 'Delivered')], max_length=50, null=True),
        ),
    ]
